### ISSUE TITLE
ClusterFps treshold

### ISSUE THREAD

**Issue by LivC193** [InformaticsMatters/pipelines#47]
Hi thank you for making this repo available. 
Can I ask you why do you set 1- args.treshold, instead of args.treshold?https://github.com/InformaticsMatters/pipelines/blob/b0830631bc77745ee5c71df2ea2c624124594802/src/python/pipelines/rdkit/cluster_butina.py#L221

https://github.com/InformaticsMatters/pipelines/blob/b0830631bc77745ee5c71df2ea2c624124594802/src/python/pipelines/rdkit/cluster_butina.py#L69
And why u use 1-x instead of x for similarity score?  ?

I think I got: It is because the RDKit implementation is for Euclidian distances rather than the OG implementation form '99.

**Comment by tdudgeon** [comment]
Yes, the RDKit [Butina.ClusterData()](http://rdkit.org/docs/source/rdkit.ML.Cluster.Butina.html?highlight=butina%20clusterdata#rdkit.ML.Cluster.Butina.ClusterData) function uses distances not similarity, so we must use 1.0 - similarity.
For all of our parameters we try to use similarity rather than distance so that we are consistent.
